version: '3.7'
networks:
  app_net:
services:
  database:
    container_name: ballpark-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      app_net:
        aliases:
          - database
  api:
    container_name: ballpark-api
    restart: always
    build: ./api
    ports:
      - '4000:4000'
    environment:
      DB_CONNECTION_STRING: mongodb://database/ballpark
      WAIT_HOSTS: database:27017
      WAIT_HOSTS_TIMEOUT: 120
    networks:
      app_net:
        aliases:
          - api
  client:
    container_name: ballpark-client
    build: ./client
    environment:
      REACT_APP_API_HTTP_URL: http://localhost:4000
      REACT_APP_API_WS_URL: ws://localhost:4000/subscriptions
      WAIT_HOSTS: api:4000
      WAIT_HOSTS_TIMEOUT: 120
    ports:
      - '3000:3000'
    networks:
      app_net:
        aliases:
          - client
  # Uncomment to enable MongoDB admin
  # admin:
  #   container_name: ballpark-admin
  #   image: 0x59/admin-mongo:latest
  #   ports:
  #     - '8082:8082'
  #   environment:
  #     - PORT=8082
  #     - CONN_NAME=database
  #     - DB_HOST=database
